version: '3'
services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgresql/data
volumes:
  postgres-storage: {}