spring:
    application:
        name: Demo
    datasource:
        url: jdbc:postgresql://localhost:5432/testdb
        username: testuser
        password: secret
otel:
    logs:
        exporter: none
    metrics:
        exporter: none
logging:
    level:
        io:
            opentelemetry:
                exporter:
                    logging: OFF