logging:
  level:
    io:
      opentelemetry:
        exporter:
          logging: 'OFF'
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,prometheus,env
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
spring:
  application:
    name: Demo
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
  jpa:
    hibernate:
      ddl-auto: update