server:
  http_listen_port: 3200
  log_level: info
stream_over_http_enabled: true
storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
distributor:
  receivers:
    otlp:
      protocols:
        http: